version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
#  mongo:
#    container_name: mongo
#    image: mongo
#    volumes:
#      - ./data:/data/db
#    ports:
#      - '27017:27017'
#    networks:
#      - app-network
  mongo:
    build:
      context: .
      dockerfile: "dockerfile-db"
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  #mongo:
  #  build:
  #    context: .
  #    dockerfile: "dockerfile-db"
  #  ports:
  #    - "27017:27017"
  #  networks:
  #    - app-network
